<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<RazorCompileOnBuild>true</RazorCompileOnBuild>
		<RazorCompileOnPublish>true</RazorCompileOnPublish>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="DartSassHost" Version="2.0.7" />
		<PackageReference Include="JavaScriptEngineSwitcher.ChakraCore" Version="3.31.0" />
		<PackageReference Include="JavaScriptEngineSwitcher.ChakraCore.Native.win-arm64" Version="3.31.0" />
		<PackageReference Include="LibSassHost" Version="1.5.0" />
		<PackageReference Include="NUglify" Version="1.21.17" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Components\AdminMenu\Default.cshtml" />
		<None Remove="Components\FilePicker\Default.cshtml" />
		<None Remove="Components\HtmlBuilder\Default.cshtml" />
		<None Remove="Components\ImagePicker\Default.cshtml" />
		<None Remove="Components\LocaleSwitcher\Default.cshtml" />
		<None Remove="Components\NotificationBar\Default.cshtml" />
		<None Remove="Components\Pagination\Default.cshtml" />
		<None Remove="Components\TopBar\Default.cshtml" />
		<None Remove="Components\VideoPicker\Default.cshtml" />
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Include="Areas\Admin\Views\Admin\Index.cshtml">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>





	<ItemGroup>
		<ProjectReference Include="..\..\core\YangOne.OTP\YangOne.OTP.csproj" />
		<ProjectReference Include="..\..\core\YangOne.Web\YangOne.Web.csproj" />
	</ItemGroup>

</Project>
