<Project>
	<PropertyGroup>
		<Version>1.0.0</Version>
		<FileVersion>1.0.0.0</FileVersion>
		<AssemblyVersion>1.00.00</AssemblyVersion>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseSharedCompilation>false</UseSharedCompilation>
	</PropertyGroup>
	<PropertyGroup Label="NuGet">
		<Authors>Binod Tamang</Authors>
		<Company>YangOne</Company>
		<Copyright>Copyright (c) Yang One Framework. All rights reserved.</Copyright>
		<PackageProjectUrl>https://github.com/YangOne-Framework/YO-Framework</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>YO;Framework;YangOne;DotNet;Web</PackageTags>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
		<RepositoryUrl>https://github.com/YangOne-Framework/YO-Framework.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>NUGET-README.md</PackageReadmeFile>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup Label="NuGetFiles">
		<None Include="$(MSBuildThisFileDirectory)..\nugetpub\icon.png" Pack="true" PackagePath="\" Visible="false" />
		<None Include="$(MSBuildThisFileDirectory)..\nugetpub\NUGET-README.md" Pack="true" PackagePath="\" Visible="false" />
	</ItemGroup>
</Project>