<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>f3abe35f-9bc9-42b2-92a3-8bc7220ef997</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\assets\js\yogridstyle.css" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\assets\js\yogridstyle.css" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\core\YangOne.Web\YangOne.Web.csproj" />
    <ProjectReference Include="..\..\Extensions\YangOne.BackgroundJobRunner\YangOne.BackgroundJobRunner.csproj" />
    <ProjectReference Include="..\..\modules\YandOne.Admin\YangOne.Admin.csproj" />
    <ProjectReference Include="..\..\modules\YangOne.Identity.Web\YangOne.Identity.Web.csproj" />
    <ProjectReference Include="..\..\modules\YangOne.IdentityServer\YangOne.IdentityServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="app_data\apiconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="app_data\cspconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="app_data\fileconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="app_data\optimizationconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="app_data\security.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="app_data\securityconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="app_data\yoconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="app_data\certs\encryption.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
